site_name: MODAQ 2.0 (M2)
docs_dir: 'src'
site_dir: 'docs'
nav:
  - Home: 'index.md'
  - Github: 'github.md'
  - Hardware: 'hardware.md'
  - Software: 'software.md'
  - Technical Reference: 'techref.md'
  - HMI: 'hmi.md'
  - Configurator: 'configurator.md'
  - Useful Links: 'links.md'
markdown_extensions:
  - footnotes
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: "__span"
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
theme:
  name: material
  features:
    - content.code.copy
  palette:
    #primary: blue
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  plugins:
  - search
  - print-site
extra_css:
  - stylesheets/extra.css